#!/bin/bash

mkdir plugins

../../mathmap -g blender 'filter ident (image in)
  in(xy)
end' plugins/plugin_ident.c

../../mathmap -g blender 'filter wave (image in, float wv: 1-100, float amp: 0-100)
  in(xy+xy:[sin(y/wv+t*2*pi),sin(x/wv+t*2*pi)]*amp)
end' plugins/plugin_wave.c
